# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
env_files:
  github_token: ~/.config/goreleaser/github_token
project_name: kube-bootstrap
builds:
  - main: main.go
    binary: kube-bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
archives:
  -
    format: tar.gz
    name_template: '{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - LICENSE
      - README.md
checksum:
    name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
sign:
  artifacts: checksum
snapshot:
    name_template: SNAPSHOT-{{ .Commit }}
release:
  github:
    owner: discreet
    name: kube-bootstrap
brews:
  -
    name: kube-bootstrap
    github:
      owner: discreet
      name: homebrew-kube-bootstrap
    description: Bootstrap your laptop for Kubernetes
    install: |
      bin.install "kube-bootstrap"
    test: |
      system "#{bin}/kube-bootstrap --version"
changelog:
  skip: false
  sort: asc
  filters:
    exclude:
      - '^docs'
